name: "Build To Branch"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-to-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Get the current branch name
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v6
        with:
          show-progress: ${{ runner.debug == 1 }}

      - name: Check if the --built branch exists
        run: |
          echo "LS_REMOTE=$( git ls-remote --heads origin ${BRANCH_NAME}--built | wc -l )" >> $GITHUB_ENV

      - name: Checkout copy of repository
        uses: actions/checkout@v6
        with:
          path: ./tmp/build-to-branch
        if: ${{ env.LS_REMOTE == 0 }}

      - name: Creating a --built branch
        if: ${{ env.LS_REMOTE == 0 }}
        run: |
          cd ${GITHUB_WORKSPACE}/tmp/build-to-branch/
          git checkout --orphan ${BRANCH_NAME}--built
          git rm --cached -r .
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      - name: Using existing --built branch
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}--built
          path: ./tmp/build-to-branch
        if: ${{ env.LS_REMOTE == 1 }}

      - name: Rsync files to build directory
        run: |
          cd "${GITHUB_WORKSPACE}"
          rsync -azrm --inplace --delete --exclude={'.git','tmp/'} --exclude-from=.deployignore ./ "${GITHUB_WORKSPACE}/tmp/build-to-branch/"

      - name: Push the files to the --built branch
        run: |
          cd ${GITHUB_WORKSPACE}/tmp/build-to-branch/
          GIT_USER_NAME="${{ github.event.pusher.name }}"
          GIT_USER_EMAIL="${{ github.event.pusher.email }}"
          if [ -z "$GIT_USER_NAME" ]; then
            GIT_USER_NAME="${{ github.actor }}"
          fi
          if [ -z "$GIT_USER_EMAIL" ]; then
            GIT_USER_EMAIL="dev@indiebranch.com"
          fi
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"
          git add -A
          MESSAGE=$( printf 'Build changes from %s\n\n%s' "${GITHUB_SHA}" "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" )
          git commit --author="${GIT_USER_NAME} <${GIT_USER_EMAIL}>" -m "${MESSAGE}"
          git push origin ${BRANCH_NAME}--built